repos:
-   repo: https://github.com/ambv/black
    rev: 19.10b0
    hooks:
    -   id: black

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    -   id: flake8
        args: [--max-line-length=120]
    -   id: check-executables-have-shebangs
    -   id: check-merge-conflict

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.761
    hooks:
    -   id: mypy
        args: [--strict]

-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
    -   id: isort

-   repo: https://github.com/pre-commit/mirrors-pylint
    rev: v2.4.4
    hooks:
    -   id: pylint
        additional_dependencies: [tabulate, bs4]

-   repo: https://github.com/asottile/pyupgrade
    rev: v1.25.2
    hooks:
    -   id: pyupgrade
        args: [--py36-plus]
