repos:
-   repo: https://github.com/ambv/black
    rev: 23.3.0
    hooks:
    -   id: black

-   repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
        args: [--max-line-length=120]

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-executables-have-shebangs
    -   id: check-merge-conflict

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.3.0
    hooks:
    -   id: mypy
        args: [--strict]

-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
    -   id: isort

-   repo: https://github.com/pre-commit/mirrors-pylint
    rev: v3.0.0a5
    hooks:
    -   id: pylint
        additional_dependencies: [tabulate, bs4]

-   repo: https://github.com/asottile/pyupgrade
    rev: v3.4.0
    hooks:
    -   id: pyupgrade
        args: [--py36-plus]
