dist: bionic
language: python
install:
  - pip install pre-commit
jobs:
  include:
    - name: pre-commit
      script:
      - pre-commit run -a
    - name: run advisor
      script:
      - pip install -r requirements.txt
      - python3 ./bin/advisor.py
